### ISSUE TITLE
Create diagram illustrating the components of the project

### ISSUE THREAD

**Issue by dylanorgeron** [davidowproject/code#11]

**Comment by dylanorgeron** [comment]
https://i.groupme.com/1191x571.png.4537ffb2ba4647bfbf2d046732fea464.large

**Comment by cassininazir** [comment]
Uploading the image directly here. 

![1191x571 png 4537ffb2ba4647bfbf2d046732fea464](https://cloud.githubusercontent.com/assets/1661430/6811960/b4b5d6d6-d239-11e4-8ab6-dd1868066603.png)

This is a really good start. Now all we need is an explanation of how this works. Let's work on that together in class today.
