### ISSUE TITLE
Create and code page wireframes

### ISSUE THREAD

**Issue by jjdoyle2010** [davidowproject/code#14]
Create simple page wire frames.

**Comment by jjdoyle2010** [comment]
@davidowproject/ui, @judyn

**Comment by summersaylor** [comment]
Y'all can follow the link below to our Google Drive Wireframes folder. Please take a look and let me know if this is what you're expecting and if anything needs to be changed. 

https://drive.google.com/open?id=0B6Vhc_NXSgDZcTYtVUdNX0pmN1U&authuser=0

**Comment by dylanorgeron** [comment]
duplicate issue exists
