### ISSUE TITLE
find js library for overly ambitious gallery proposal 

### ISSUE THREAD

**Issue by dylanorgeron** [davidowproject/code#16]

**Comment by judyn** [comment]
I found these two js libraries: Masonry http://masonry.desandro.com/ 
and Isotope http://isotope.metafizzy.co/

Hopefully that's the right thing we're looking for!

**Comment by cassininazir** [comment]
Recommend isotope over masonry. Both are actually quite straightforward to implement.

Flickity is also nice but have not used http://flickity.metafizzy.co/http://flickity.metafizzy.co/

Cassini

**Comment by judyn** [comment]
going w/ isotope for the time being, found this angularJS library for isotope that i will attempt to figure out https://github.com/mankindsoftware/angular-isotope
