### ISSUE TITLE
create thumbnails for all images

### ISSUE THREAD

**Issue by dylanorgeron** [davidowproject/code#17]

**Comment by dylanorgeron** [comment]
find average thumbnail size on smart phones, save them at that size, and upload as a zip to google drive so i can look at file size and decide what we are going to do

**Comment by judyn** [comment]
@Adunkadu Don't worry about this anymore I think we're able to pull thumbnails from the JSON data, thanks!

**Comment by cassininazir** [comment]
There are WordPress plugins that can also generate these images in batch and post to website if this is still needed.

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas
