### ISSUE TITLE
Figure out how to use the angularJS library for isotope

### ISSUE THREAD

**Issue by judyn** [davidowproject/code#23]
https://github.com/mankindsoftware/angular-isotope

http://mankindsoftware.github.io/angular-isotope/index.html

**Comment by cassininazir** [comment]
These are perfect, Judy. Well done. Using the second link that you provided as a guide, the filters for this project might map to these categories:
-   Sculpture
-   Painting
-   Drawing
-   Mixed media
-   Photography
-   etc (might reference http://www.visual-arts-cork.com/art-types.htm#types)

And you might also allow sort based on:
-   Alpha by artist
-   Alpha by piece
-   Date (you may need @dylanorgeron's help to convert to UNIX timestamp -- see http://www.unixtimestamp.com)

**Comment by judyn** [comment]
working out the kinks, basically figured out
