### ISSUE TITLE
Save all images locally

### ISSUE THREAD

**Issue by jjdoyle2010** [davidowproject/code#24]
Also create consistent naming convention.

**Comment by jjdoyle2010** [comment]
All the images that I could find I saved, organized and renamed them. Just need to wait on the research team to find what other pieces are being displayed and to get images of them to me.

**Comment by cassininazir** [comment]
Thanks, James. Post to Google Drive if you haven�t already.

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas

**Comment by jjdoyle2010** [comment]
We're still missing images.

**Comment by cassininazir** [comment]
Create a task for the research team (ask Sruthi to assign) for the images needed and the location, if you have.

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas

**Comment by judyn** [comment]
oops my b!

**Comment by dylanorgeron** [comment]
@jjdoyle2010, please create a folder in the 'img' folder to store all of the pictures you have saved and commit it in the working branch
