### ISSUE TITLE
Work on wireframes not currently being worked on

### ISSUE THREAD

**Issue by jjdoyle2010** [davidowproject/code#25]
Currently Home, Nav, Map, Tutorial, About, Settings, Profile.

**Comment by judyn** [comment]
let me know if you need help!

**Comment by summersaylor** [comment]
New site map attached. Will attach new wireframes next. 

![sitemap](https://cloud.githubusercontent.com/assets/10950415/7047906/38e4e72a-ddd5-11e4-8b50-071e94ee8aad.png)

**Comment by summersaylor** [comment]
New Wireframes. About screen is not shown, but will follow the same format as Art Info Screen.
![wireframes new1](https://cloud.githubusercontent.com/assets/10950415/7048147/b8fb5790-ddd6-11e4-9123-49dabc67e09c.jpg)

**Comment by summersaylor** [comment]
Updated Gallery View With Filter Scroll.

![galleryfilteroptions](https://cloud.githubusercontent.com/assets/10950415/7057297/f0908340-de19-11e4-98ca-551094ad2cff.jpg)

**Comment by judyn** [comment]
it's my understanding that @jjdoyle2010 is working solely on the website now, correct?

**Comment by summersaylor** [comment]
Yes. He has access to our notes, sitemap, mood board, etc. It's all in the Drive and he knows we (UI team) can help if he needs it.
