### ISSUE TITLE
map page - TBA

### ISSUE THREAD

**Issue by dylanorgeron** [davidowproject/code#29]

**Comment by summersaylor** [comment]
@greyhound77 provide Dylan O. with 2 kinds of maps for each floor; one with prospective estimote locations and one empty map. (8 png's total)

**Comment by summersaylor** [comment]
Dylan C. map out pieces on 3rd and 4th floor. Make sure to write down which room number the piece is nearest and mark which wall it is on on the map. I'll take care of floors 1 and 2.

**Comment by greyhound77** [comment]
![floors](https://cloud.githubusercontent.com/assets/10950421/10955122/5a38fd66-8317-11e5-9b98-b1cae0147b8d.png)
