### ISSUE TITLE
Deploy current build to every iOS device in class

### ISSUE THREAD

**Issue by cassininazir** [davidowproject/code#30]
Let's do this about an hour into class. Would like you to inventory every kind of device we have as well.

Excellent chart you created at https://docs.google.com/spreadsheets/d/1k9bhu8B41LSeWNcCoABWMLTQrFVQmG32VYN-GEZ39LA/edit#gid=0

**Comment by linamoon** [comment]
Got the latest code working on my iTouch! iOS 6.1.3. It looks quite different from the version from last week, I wonder if all the features are working.
