### ISSUE TITLE
Look into showing status bar on iOS7+

### ISSUE THREAD

**Issue by linamoon** [davidowproject/code#31]

**Comment by linamoon** [comment]
Status bar showing:
- Lina's iTouch, 6.1.3

Status bar hidden:
- Cassini's 4S, 8.1.2
- Cassini's 5C, 8.2
- Jeremy's 4, 7.1.2

To test:

**Comment by h1r0sh1m4** [comment]
http://devgirl.org/2014/07/31/phonegap-developers-guid/

**Comment by cassininazir** [comment]
Looks like PhoneGap also has a plugin 

https://github.com/phonegap-build/StatusBarPlugin/blob/master/README.md

**Comment by dylanorgeron** [comment]
status bar always shown now
