### ISSUE TITLE
Purchase Estimotes

### ISSUE THREAD

**Issue by cassininazir** [davidowproject/code#33]
Purchase enough estimotes to blanket first floor Davidow Collection at minimum. Find funding for additional as needed.

**Comment by cassininazir** [comment]
Sent email to business@estimote.com inquiring about educational pricing.

**Comment by summersaylor** [comment]
@judyn Get numbers from Cassini about cost of estimotes, how many we need, etc.

**Comment by judyn** [comment]
e-mailed Brett Roby 10/1, no response as of today :) Should we just wait to ask in person?

**Comment by summersaylor** [comment]
Yea, we'll set aside time at the end of Thursdays meeting to go find him.

**Comment by cassininazir** [comment]
Good. Don't let me go over on time!

**Comment by dylanorgeron** [comment]
bought radbeacons instead
