### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by judyn** [davidowproject/code#35]
all you bro @dylanorgeron

**Comment by dylanorgeron** [comment]
drop push notifications, wire up day night cycles

**Comment by judyn** [comment]
day mode should be from 9am - 5pm

**Comment by summersaylor** [comment]
@dylanorgeron @judyn Make a list of possible push notifications and other settings there may be for next class.

**Comment by summersaylor** [comment]
don't have a need for this page.
