### ISSUE TITLE
Figure out why typography is different on Jeremy's iPhone 6 (iOS 8.2)

### ISSUE THREAD

**Issue by linamoon** [davidowproject/code#37]
Duncan has the same iOS version (8.2) and the UI team's fonts are showing up his phone, but it looks like Jeremy's iPhone 6 changes them to Helvetica.

**Comment by linamoon** [comment]
Fonts UI team are using:

Oswald Regular - Headers
http://www.google.com/fonts#UsePlace:use/Collection:Oswald

Open Sans Regular - Normal (Paragraph)
http://www.google.com/fonts#UsePlace:use/Collection:Open+Sans

**Comment by cassininazir** [comment]
Iosfonts.comhttp://Iosfonts.com lists fonts available on the OS. Will need to include these font files in te build. Not include as href from Google Fonts

Sent from my iPhone

On Apr 9, 2015, at 12:22 PM, Lina Moon <notifications@github.com<mailto:notifications@github.com>> wrote:

Fonts UI team are using:

Oswald Regular - Headers
http://www.google.com/fonts#UsePlace:use/Collection:Oswald

Open Sans Regular - Normal (Paragraph)
http://www.google.com/fonts#UsePlace:use/Collection:Open+Sans

�

**Comment by cassininazir** [comment]
To clarify my earlier comment, when in Airplane mode the fonts won't download from the web. Best practice is to include font files inside the app.

Sent from my iPhone

On Apr 9, 2015, at 12:22 PM, Lina Moon <notifications@github.com<mailto:notifications@github.com>> wrote:

Fonts UI team are using:

Oswald Regular - Headers
http://www.google.com/fonts#UsePlace:use/Collection:Oswald

Open Sans Regular - Normal (Paragraph)
http://www.google.com/fonts#UsePlace:use/Collection:Open+Sans

�
