### ISSUE TITLE
Can we actually release our app?

### ISSUE THREAD

**Issue by dylanorgeron** [davidowproject/code#41]
Research guidelines for releasing app.

**Comment by dylanorgeron** [comment]
iOS says no, android says we have to own the site we show

**Comment by cassininazir** [comment]
@dylanorgeron provide some links to this. Is this because of web view?

**Comment by judyn** [comment]
Launch Checklist and Core App Quality guidelines for Android:

http://developer.android.com/distribute/tools/launch-checklist.html
http://developer.android.com/distribute/essentials/quality/core.html
