### ISSUE TITLE
Merge repos into code

### ISSUE THREAD

**Issue by dylanorgeron** [davidowproject/code#43]

**Comment by dylanorgeron** [comment]
@judyn @summersaylor @linamoon @greyhound77 The theme files are already included in the code repo from last semester. The less files were not carried over and are currently outdated. Let me know if you guys want to continue using less and I'll see about updating them. It may be easier to just use the new files and write in css from this point on.

**Comment by judyn** [comment]
I'd like to look into learning Sass, but it doesn't really matter I guess

**Comment by summersaylor** [comment]
I'm cool with continuing using Less, learning Sass, or moving to straight
CSS. If you think it'll just be easier to use CSS then we'll make the
changes.
