### ISSUE TITLE
Mock up a bottom nav bar

### ISSUE THREAD

**Issue by judyn** [davidowproject/code#47]
Either mock one up in photoshop, draw a sketch, or straight up make one using HTML/CSS and post it here on or the drive :)

**Comment by greyhound77** [comment]
![mock_up](https://cloud.githubusercontent.com/assets/10950421/9919482/cecb08be-5c92-11e5-8686-dfef1e84f650.jpg)

**Comment by cassininazir** [comment]
Love the colours. The icons are clear and legible. Two things:
- Change text to uppercase
- The explore icon doesn't seem to fit. Not sure what to replace but a world isn't quite the right metaphor for this.

**Comment by greyhound77** [comment]
I know we mentioned using a combination of icons and words, but I included one without just for the sake of comparison. Also, our original nav includes 6 menu items so I picked what I assumed would be the most used without the nav bar becoming too cluttered. Could we somehow mash the "about" and "tutorial" in with the "settings" page? Lastly, I'm not so sure about the readability of the light blue on the white background. What do y'all think?

**Comment by greyhound77** [comment]
![nav_u1](https://cloud.githubusercontent.com/assets/10950421/9920134/27acf114-5c97-11e5-9fc7-4c38b68a4003.jpg)

**Comment by greyhound77** [comment]
Mashed two icons together to make a new explore button. Thoughts?

**Comment by judyn** [comment]
Nicely done Dylan!! 

I like the explore icon, although the first thing that came to my mind was that someone would mistake it for "Search". Maybe binoculars or a compass? (Yes, I googled "explore icon").

Also, I think that since we seem to be leaning towards the light theme, that it would make sense to have the nav bar contrast. Just my two cents!

**Comment by summersaylor** [comment]
Dylan - update the explore icon possibly with the binoculars from font awesome.
As per meeting: Stick with black menu and words under icons.

**Comment by greyhound77** [comment]
![binoc_nav](https://cloud.githubusercontent.com/assets/10950421/10058424/01e7430c-620b-11e5-8f6a-d9627b10ce7f.jpg)

**Comment by summersaylor** [comment]
Looks good! Can you drop the styles for that into the css and get judy to
add it to the other code so we can put some tests together tomorrow?

**Comment by summersaylor** [comment]
@dylanorgeron - When on a page, make the menu button for that page show in inverse colors (or some other different style from the rest of the menu).

**Comment by summersaylor** [comment]
@judyn @greyhound77  - Make font for menu icons thicker to be more legible.

**Comment by summersaylor** [comment]
This is the new version with a medium font thickness. Really need to see it in the app or on a small screen to be sure.

![mock_4 medium text](https://cloud.githubusercontent.com/assets/10950415/10224244/bfccd748-6822-11e5-8db6-cb0b210fedbe.jpg)

**Comment by summersaylor** [comment]
Version with larger size font (from 3 to 6) and High/Low text. 
![nav_bar_highlow](https://cloud.githubusercontent.com/assets/10950415/10226258/130416de-682c-11e5-8035-764f864f9b95.jpg)

**Comment by summersaylor** [comment]
@dylanorgeron use img files (to be provided by @greyhound77 ) to make an updated nav bar with imgs and text. We will finish this menu bar just in case we don't go with one of the new ideas next week. Dylan C. make the icons into hi-res SVG's and all in the blue color, without text.

**Comment by summersaylor** [comment]
@greyhound77 working with css keyframes. Check out my codepen for a starting point --> http://codepen.io/summersaylor/pen/YXKpjR

**Comment by cassininazir** [comment]
Interesting navigation animation here 

https://dribbble.com/shots/1977075-New-app-Menu-Interaction

**Comment by greyhound77** [comment]
<img width="2106" alt="screen shot 2015-11-16 at 12 22 26 am" src="https://cloud.githubusercontent.com/assets/10950421/11175499/858e1958-8bf8-11e5-8745-ac3ed1a4d988.png">

**Comment by greyhound77** [comment]
<img width="2106" alt="update_icons" src="https://cloud.githubusercontent.com/assets/10950421/11175511/9cb2d722-8bf8-11e5-9c44-01f37d6ee7ee.png">

**Comment by dylanorgeron** [comment]
dropped
