### ISSUE TITLE
Recolor logo

### ISSUE THREAD

**Issue by judyn** [davidowproject/code#48]
Recolor logo to match light theme. Feel free to mock up any different designs if you so please :)

**Comment by summersaylor** [comment]
Testing 2 logos on usability hub (icons 5 and 6)
icon 5
![icon5-2](https://cloud.githubusercontent.com/assets/10950415/9945771/ec907a38-5d54-11e5-85e5-389f3eef7ffb.PNG)
icon 6
![icon6-2](https://cloud.githubusercontent.com/assets/10950415/9945773/edb3138a-5d54-11e5-9254-288e7e9621db.PNG)

**Comment by summersaylor** [comment]
Test between icons 5 and 6:
https://usabilityhub.com/tests/d3fe205ed54e/results
17/27 preferred icon 6. The choice has been made.
