### ISSUE TITLE
Retrieve Data from JSON File for Davidow Project

### ISSUE THREAD

**Issue by cassininazir** [davidowproject/code#5]
@thecvincent, Added you to the Davidow Project space. Could you produce a JSON data file for the Davidow Project (similar to the ones at http://atec.io/api)?

**Comment by thecvincent** [comment]
There is now an active endpoint at http://www.utdallas.edu/davidow/json

A nice way to look at and validate JSON is by using JSONLint (http://jsonlint.com/)

The image data is serilaized. There's a simple unserialize function in php to turn it back into an object. 

Let me know if this data structure does not meet your needs.

**Comment by cassininazir** [comment]
@linamoon @h1r0sh1m4 I believe you both were working the JSON file. I can assign tasks to only one individual at a time unfortunately. 

See above comment for the location for the JSON file and review Charles' comments. Charles is the web developer who created the database housing the content and JSON file. You may message him @thecvincent if you have questions about the structure (or think about suggested changed).  

Goal here is to parse the JSON file and retrieve the information. Ideally, want you be able to do three things:
1. Display a full list of information artists and work from the JSON file in an HTML file (do not add any CSS styles)
2. Be able to click an item on the HTML file that you created and pull full details of each item
3. Be able to sort the full list alphabetically (by last name) or by work.
