### ISSUE TITLE
Remove pieces that aren't in the ATEC building

### ISSUE THREAD

**Issue by judyn** [davidowproject/code#57]
I believe all the pieces that don't have an image associated with it aren't in the ATEC building, according to the doc that Research made last semester https://docs.google.com/document/d/1NahKERi3A7kJW20JmX7Cs3fDQTv_GXAP3piZxWlKAkk/edit?usp=sharing

Might as well remove them from the app if you can't find em in the building right?

**Comment by summersaylor** [comment]
Completed by Dylan O.
