### ISSUE TITLE
App Appearance Updates

### ISSUE THREAD

**Issue by summersaylor** [davidowproject/code#59]
@dylanorgeron - Take out the header row in the app (the menu icon being highlighted is sufficient to identify the page the user is on) and make art on Art Info screen enlarge upon double tap or click on a fill screen button.

**Comment by summersaylor** [comment]
@dylanorgeron @greyhound77 @judyn - have sketches for Art Info screen by next meeting. think about a back button for apples, possible menu icons, different fonts for header copy specifically, larger margins, and where can you add motion.

**Comment by summersaylor** [comment]
@judyn and myself - make mock-ups of the below design with these things in mind... 
- no notification bar at top of screen
- call to action for tweeting functionality
- left justification
- card style information
- swiping nav/other nav options

This is where we left off in the meeting
![screen 2](https://cloud.githubusercontent.com/assets/10950415/10237498/f3c6cc70-6877-11e5-810a-df24f43b3418.PNG)

**Comment by summersaylor** [comment]
- warmer grey (use some yellow)
- better layout of info

upload to drive by Sunday night so we can text bout it Monday

**Comment by judyn** [comment]
Nice overview of mobile ui/ux trends in 2015 https://medium.com/interactive-mind/mobile-2015-263ab694e60e

**Comment by summersaylor** [comment]
Art Info
![artinfo](https://cloud.githubusercontent.com/assets/10950415/10678054/87347ea4-78d5-11e5-8fb3-8bbab2cc9258.png)

Gallery
![gallery](https://cloud.githubusercontent.com/assets/10950415/10678055/8894a3aa-78d5-11e5-82cf-8b04093b7c1e.png)

**Comment by summersaylor** [comment]
Gallery Sort View
![gallerysort](https://cloud.githubusercontent.com/assets/10950415/10682420/324e9e08-78fb-11e5-96e8-a6e618c107de.png)
