### ISSUE TITLE
Update Dev database

### ISSUE THREAD

**Issue by thecvincent** [davidowproject/code#8]
create dev clone of davidow for development

**Comment by judyn** [comment]
I believe Dylan said he has access to the database now.?

**Comment by cassininazir** [comment]
Correct.

**Comment by judyn** [comment]
Dylan, here are the links to the Map ID's that the research team put together in Spring, this is what you were talking about having them do right? Update database if this is the info we need, pls ty. 

https://docs.google.com/document/d/1NahKERi3A7kJW20JmX7Cs3fDQTv_GXAP3piZxWlKAkk/edit?usp=sharing

https://drive.google.com/file/d/0B0KmCkuWHgGAOHdfck9udFJKazA/view?usp=sharing
