### ISSUE TITLE
Complete the CodeSchool course on angularjs

### ISSUE THREAD

**Issue by dylanorgeron** [davidowproject/code#9]
https://www.codeschool.com/courses/shaping-up-with-angular-js

Complete the course and post a screenshot of your badge as a comment.

**Comment by EJGrams** [comment]
![badge1](https://cloud.githubusercontent.com/assets/10986219/6692143/eaab9344-cc98-11e4-8a07-5b89cde60375.JPG)

**Comment by EJGrams** [comment]
![coursecompleteionbadge](https://cloud.githubusercontent.com/assets/10986219/6713175/ab212646-cd5e-11e4-9e90-4cb2c1a6ab5e.JPG)

**Comment by cassininazir** [comment]
Nice job, @EJGrams. Hope others have had a chance to complete.

**Comment by judyn** [comment]
bam
![](http://ft.trillian.im/48a0cd6ab5ab67b43c361f24485eebba90331ece/6xkO2iMbvA6kuJ8mrX86BuPUCLGPu.jpg)

**Comment by cassininazir** [comment]
Rock on!

Sent from my iPhone

On Mar 27, 2015, at 12:57 AM, Judy <notifications@github.com<mailto:notifications@github.com>> wrote:

bam
[https://camo.githubusercontent.com/be7d4fe1b187d87a721526425ba4fbe1565a9658/687474703a2f2f66742e7472696c6c69616e2e696d2f343861306364366162356162363762343363333631663234343835656562626139303333316563652f36786b4f32694d627641366b754a386d7258383642755055434c4750752e6a7067]https://camo.githubusercontent.com/be7d4fe1b187d87a721526425ba4fbe1565a9658/687474703a2f2f66742e7472696c6c69616e2e696d2f343861306364366162356162363762343363333631663234343835656562626139303333316563652f36786b4f32694d627641366b754a386d7258383642755055434c4750752e6a7067

�
